### PR TITLE
Stories/272 pre difi

### PR DESCRIPTION
**Pull request by cguardia**
Adding a generic DIFI after the instructions but before the waiting room, record responses in questions table.

### CODE REVIEW

**Comment by vlall** [comment]
I believe this is now rebased correctly, testing underway.

**Comment by vlall** [comment]
I'm having trouble getting this branch to work, perhaps it was a merge error.

**Comment by cguardia** [comment]
Can you give me more details? Is the problem the failed checks after committing, or is the new feature not working at all?

**Comment by vlall** [comment]
I receive and internal server error when running the experiment. I think perhaps its a merge conflict with the template.

**Comment by vlall** [comment]
After fixing the template issue, i'm having trouble getting past the instructions page... The Begin button is not working and there isn;t any traceback from the terminal window.

**Comment by vlall** [comment]
Perhaps i should undo my rebase and let you do a new rebase? That may be easier for you.

**Comment by cguardia** [comment]
Doesn't look like you undid the rebase. I could just do a new branch of master and apply the two commits there, to avoid more rebase headaches.

**Comment by vlall** [comment]
I believe I fixed this, testing again.

**Pull request merged**
