### PR TITLE
Advantage seeking bots should avoid walls

### PR DESCRIPTION
**Pull request by MatthewWilkes**
This implements story 337, allowing advantage seeking bots to traverse spaces that contain walls. This attempts to mitigate against some of the worse failure modes regarding large, complex grids but it's not guaranteed to do so.

It also fixes a bug causing high performance bots to perform an order of magnitude worse than expected.d

### CODE REVIEW

**Comment by alecpm** [comment]
I made a fix for Python 3. The bot players weren't moving on Python 3, which indicates we probably need more tests for this code. This appears to be working, and the code looks reasonable (though I can't say I fully understand the algorithm being used).

Unfortunately, it also seems to be quite slow when running locally. I think it may make sense to limit the search to a relatively small number of moves. The random moves should probably also account for adjacent walls to avoid turns lost to collisions.

**Comment by alecpm** [comment]
For some mazes pretty low values (e.g. 100) of `max_iterations` seem to provide reasonable bot behavior with better performance. In denser more contiguous mazes, higher values are likely more appropriate. Perhaps this should be a config parameter.

Mostly unrelated to this story, perhaps the bot should have some safeguard to prevent if from just moving back and forth over the same two squares. This seems to be happening in some cases when no food is detectable within `max_iterations`. The player spread increasing mechanism may need a fix to handle cases where the players current position provides something like a local minimum in player spread. My last 4-bot 49x49 grid run had one bot in a relatively closed part of the maze just going up and down over two squares for the entire duration.

**Comment by MatthewWilkes** [comment]
I believe this failing test was due to being out-of-sync with master. I've rebased and it looks better, pushed now and waiting to see if travis agrees with me.

I've added some tests to address @alecpm's comments about poor testing. I agree there.

We only calculate all those distances when we don't have a piece of food we're going for, but it's a good point, I'd forgotten that it calculates for all players not just the current one. I think the suggestion will work.

**Comment by MatthewWilkes** [comment]
The failing tests here are because one of the method signatures changed in the work for #176. Once that's merged this should go away, we're only seeing it currently as the Dallinger half is merged but the GU half isn't.

**Comment by vlall** [comment]
Tests are still broken for this..

**Comment by MatthewWilkes** [comment]
@alecpm said in the call yesterday that he was okay with moving this forward, but I think we need to make a story to cover his suggested optimisations

**Comment by MatthewWilkes** [comment]
Okay, this is a bit ridiculous. This PR is now passing, but one with literally zero changes is failing. I think this is good to merge, @vlall

**Pull request merged**
