### PR TITLE
Re-create https://github.com/Dallinger/Griduniverse/pull/277/ off the main branch

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/Dallinger/Griduniverse/issues/268 https://github.com/Dallinger/Griduniverse/issues/269

### CODE REVIEW

**Review by alecpm — APPROVED** [review]
Looks fine. I got a little confused by the re-ordering of params, which looked like a mass removal at first. That's probably going to cause some merge conflicts with open PRs, but they should be simple enough to resolve.

**Review by alecpm — CHANGES_REQUESTED** [review]
Spoke too soon, there's a conflict that needs to be resolved before this can be merged.

**Comment by jessesnyder** [comment]
I think this PR is now redundant with already merged work:
https://github.com/Dallinger/Griduniverse/pull/296

@stugots Does that sound right to you?

**Comment by ghost** [comment]
@jessesnyder Yes

**Comment by jessesnyder** [comment]
Redundant with https://github.com/Dallinger/Griduniverse/pull/296

**Pull request closed without merging**
