### PR TITLE
Add demo for looped experiment

### PR DESCRIPTION
**Pull request by vlall**
Adds a demo that runs a looped game of griduniverse for 10 iterations for 10 participants per game. This shows the high-level API is capable of looping through experiments.

### CODE REVIEW

**Comment by vlall** [comment]
So I can run this in sandbox, but when deploying, I get this error:
```
❯❯ Launching the experiment on the remote server and starting recruitment...
/Users/users/.virtualenvs/d2/lib/python2.7/site-packages/urllib3/util/ssl_.py:335: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Users/users/.virtualenvs/d2/lib/python2.7/site-packages/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

❯❯ Experiment launch failed, check web dyno logs for details.

❯❯ Failed to open recruitment, check experiment server log for details: Can't run an MTurk HIT in debug mode.
Traceback (most recent call last):
  File "loop_exp.py", line 12, in <module>
    num_dynos_worker=participants,
  File "/Users/users/prog/dev/Dallinger/dallinger/experiment.py", line 49, in new_meth
    return meth(self, *args, **kwargs)
  File "/Users/users/prog/dev/Dallinger/dallinger/experiment.py", line 471, in run
    exp_config=self.exp_config
  File "/Users/users/prog/dev/Dallinger/dallinger/command_line.py", line 591, in deploy_sandbox_shared_setup
    launch_data = _handle_launch_data('{}/launch'.format(heroku_app.url))
  File "/Users/users/prog/dev/Dallinger/dallinger/command_line.py", line 471, in _handle_launch_data
    launch_request.raise_for_status()
  File "/Users/users/.virtualenvs/d2/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://dlgr-fb3c15e8.herokuapp.com/launch
```

**Comment by jessesnyder** [comment]
@vlall I'm not sure this is a bug. This would happen if you run `dallinger deploy` (or `dallinger sandbox` I would think), but your config file indicates debug mode. Is this the case here?

I considered ignoring the value of `mode` when the MTurkRecruiter runs, but it seemed that when in doubt (meaning, contradictory configuration), we should assume the *most conservative path*, so I left that check in, and bail out with an error.

**Comment by vlall** [comment]
There is no config file other than the parameters specified in `experiment.run`, which specifies `deploy`. What's strange is this works with `mode=sandbox` as a parameter but not `mode=deploy`.

**Comment by suchow** [comment]
@vlall Try `live` instead of `deploy`.

**Comment by jessesnyder** [comment]
We should change the exception message here:
```
raise MTurkRecruiterException("Can't run an MTurk HIT in debug mode.")
```
It should say something like: "[blah] was not a valid mode for MTurk recruitment.  Mode must be either 'sandbox' or 'live'"

**Pull request merged**
