### PR TITLE
Stories/268 ingroup donation

### PR DESCRIPTION
**Pull request by jessesnyder**
Introduces a new config variable `donation_ingroup`. If present, a "My Group" donation button will appear during donation rounds. If both `donation_ingroup` and `donation_group` are true, the `Group` donation button which requires selecting a player is not displayed, so there will never by two group donation buttons present.

Config values helpful for testing:

```
max_participants = 4
alternate_consumption_donation = true
donation_amount = 1
donation_ingroup = true
donation_public = true
score_visible = true
num_rounds = 4
time_per_round = 25
num_colors = 2
```

### CODE REVIEW

**Comment by jessesnyder** [comment]
Note that there is some near-overlap between this PR and #144, so some care will need to be taken with merging.

**Comment by suchow** [comment]
@jessesnyder Double check the PR number referenced in your last comment? I'm pretty sure the current PR has quite a bit more than *some* overlap with #144. :)

**Comment by jessesnyder** [comment]
The robot-based test passes for me locally, but is again hanging-then-failing on Travis.

**Comment by jessesnyder** [comment]
@suchow This should now be working correctly for the case where donations are enabled, but alternate_donation_consumption is false.

**Comment by suchow** [comment]
(Fixed for me.)

**Pull request merged**
