### PR TITLE
Story 234 - Replay Griduniverse game

### PR DESCRIPTION
**Pull request by alecpm**
## Description
Implements support for replaying Griduniverse games, using the commandline. I recommend testing this by running a new Griduniverse game (older exports will be missing chat data):

    cd dlgr/griduniverse
    dallinger debug

Record the **experiment_id** and export the data:

    dallinger export --app **experiment_id** --local

Run the replay:

    dallinger load --app **experiment_id** --replay

## Motivation and Context
This, along with the [Dallinger branch](https://github.com/Dallinger/Dallinger/tree/stories/234-replay) implements generic replay support for experiments along with specific support for replaying Griduniverse games in a browser as described in [ScrumDo Story 234](https://app.scrumdo.com/projects/story_permalink/1268252)

## How Has This Been Tested?
The Dallinger branch implements new unit tests for the replay handler module and integration tests for the commandline `--replay` flag and loader. It has also been tested manually by running Griduniverse experiments, exporting them, and then loading them with the new `--replay` flag.

### CODE REVIEW

**Comment by suchow** [comment]
screenshot 2017-08-22 11 33 15

**Comment by alecpm** [comment]
It certainly shouldn't be making participants spectators, though it would if you have the `replay` config variable set to` true` during the experiment run.  How are you running the experiment and what is in your config?

I'll try to reproduce locally.

**Comment by suchow** [comment]
@alecpm I'm running this PR in combination with the associated Dallinger branch, config unchanged, browser cache cleared.

**Comment by suchow** [comment]
@alecpm And I'm running `dallinger debug --verbose`

**Comment by alecpm** [comment]
Should be fixed now.

**Comment by suchow** [comment]
Hm, not sure how this broke the build once merged into `master` given that it was green here.

**Comment by alecpm** [comment]
Looks like some of the test infrastructure on Dallinger master changed since the last time tests were run on this branch. Just committed a fix on GU master, but I think a fix is also needed in Dallinger master.

**Pull request merged**
