### PR TITLE
Story 299: Support scrubbing back in time

### PR DESCRIPTION
**Pull request by MatthewWilkes**

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
This requires https://github.com/Dallinger/Dallinger/pull/967 but is ready for review

**Comment by alecpm** [comment]
This seems to be causing some python 2 only test failures `TypeError: 'NoneType' object has no attribute '__getitem__'` in `json.loads` in a couple places.

**Comment by MatthewWilkes** [comment]
I think these were transient failures because of something in Dallinger, I saw them on other PRs too and they're no longer showing up.

**Comment by MatthewWilkes** [comment]
Maybe not. They're passing for me locally but not on Travis

**Pull request merged**
